/***** CREATE TABLE 실습 ******/

-- 고객 테이블 CUSTOMER
CREATE TABLE CUSTOMER(
    CUSTOMER_ID NUMBER(10,0) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,
    CUSTOMER_EMAIL VARCHAR2(100) CONSTRAINT CUSTOMER_EMAIL_U UNIQUE,
    CUSTOMER_PHONE VARCHAR2(20),
    CONSTRAINT CUSTOMER_PHONE_U UNIQUE(CUSTOMER_PHONE),
    CUSTOMER_ADDRESS VARCHAR2(225)
    );
    
COMMENT ON COLUMN "CUSTOMER".CUSTOMER_ID IS '고객아이디'; -- 주석작성
COMMENT ON COLUMN "CUSTOMER".CUSTOMER_NAME IS '고객이름'; -- 주석작성
COMMENT ON COLUMN "CUSTOMER".CUSTOMER_EMAIL IS '고객이메일'; -- 주석작성
COMMENT ON COLUMN "CUSTOMER".CUSTOMER_PHONE IS '고객핸드폰번호'; -- 주석작성
COMMENT ON COLUMN "CUSTOMER".CUSTOMER_ADDRESS IS '고객주소'; -- 주석작성
/*
테이블 이름엔 " " 를 넣어도 문제가 없지만
소문자면 지워주고 해야함
대문자라 " " 해도 상관없음
안넣어 주는 것이 가장 좋음
*/
COMMIT;

-- PRODUCT 테이블 생성
-- PRODUCT_ID NUMBER(10,0) 기본키
-- PRODUCT_NAME VARCHAR(100) NULL 사용 불가
-- PRODUCT_PRICE NUMBER(소수점 2째 자리까지 허용) NULL 사용 불가
-- PRODUCT_DESC VARCHAR(200) -- 중복 안되는 특별한 값 설정

-- PRODUCT 값 추가
-- 아메리카노 3000  신선한 원두로 만든 아메리카노
-- 카페라테   2500  부드러운 우유가 들어간 라테
-- 카푸치노  3500  진한 커피와 거품이 어우러진 카푸치노
-- 카라멜 마키아토 4000  달콤한 카라멜 시럽이 들어간 마키아토

CREATE TABLE PRODUCT(
    PRODUCT_ID NUMBER(10,0) CONSTRAINT P_I_P PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    PRODUCT_PRICE NUMBER(10,2) NOT NULL,
    PRODUCT_DESC VARCHAR2(200) CONSTRAINT PRODUCT_DESC_U UNIQUE
    );
    
INSERT INTO PRODUCT VALUES (1,'아메리카노',3000,'신선한 원두로 만든 아메리카노');
INSERT INTO PRODUCT VALUES (2,'카페라테',2500,'부드러운 우유가 들어간 라테');    
INSERT INTO PRODUCT VALUES (3,'카푸치노',3500,'진한 커피와 거품이 어우러진 카푸치노');
INSERT INTO PRODUCT VALUES (4,'카라멜 마키아토',4000,'달콤한 카라멜 시럽이 들어간 마키아토');




-- FOOD_COMPANY TABLE 생성
CREATE TABLE FOOD_COMPANY(
    COMPANY_ID NUMBER(10,0) PRIMARY KEY, -- 회사 아이디로 기본키
    COMPANY_NAME VARCHAR2(100) NOT NULL, -- 회사 이름 (NULL 불가)
    COMPANY_ADDRESS VARCHAR2(225), -- 회사 주소
    COMPANY_PHONE VARCHAR2(20)   -- 회사 전화번호
);

-- SNACKS 테이블 생성
CREATE TABLE SNACKS(
    SNACK_ID NUMBER(10,0) PRIMARY KEY, -- 과자ID (키본키)
    SNACK_NAME VARCHAR2(100) NOT NULL, -- 과자 이름 (NULL 불가)
    PRICE NUMBER(10,2) NOT NULL, -- 가격 (NULL 불가)
    COMPANY_ID NUMBER(10,0), -- 핵심포인트
    CONSTRAINT FK_COMPANY FOREIGN KEY(COMPANY_ID)
    REFERENCES FOOD_COMPANY(COMPANY_ID) ON DELETE CASCADE
    -- FOOD_COMPANY 회사 ID ON DELETE CASCADE -- 부모 삭제시 자식까지 삭제해줘
);
--> ORA-00904: COMPANY_ID NUMBER(10,0), -- 핵심포인트
---> 부모에서 COMPANY_ID 자식에서도 COMPANY_ID 쓰지않아도 됨

CREATE TABLE SNACKS1(
    SNACK_ID NUMBER(10,0) PRIMARY KEY, -- 과자ID (키본키)
    SNACK_NAME VARCHAR2(100) NOT NULL, -- 과자 이름 (NULL 불가)
    PRICE NUMBER(10,2) NOT NULL, -- 가격 (NULL 불가)
    CCCCCCCCC NUMBER(10,0), -- 핵심포인트
    CONSTRAINT FK_COMPANY1 FOREIGN KEY(CCCCCCCCC)
    REFERENCES FOOD_COMPANY(COMPANY_ID) ON DELETE CASCADE
    -- FOOD_COMPANY 회사 ID ON DELETE CASCADE -- 부모 삭제시 자식까지 삭제해줘
);

CREATE TABLE SNACKS2(
    SNACK_ID NUMBER(10,0) PRIMARY KEY, -- 과자ID (키본키)
    SNACK_NAME VARCHAR2(100) NOT NULL, -- 과자 이름 (NULL 불가)
    PRICE NUMBER(10,2) NOT NULL, -- 가격 (NULL 불가)
    AAAAAA NUMBER(10,0), -- 핵심포인트
    CONSTRAINT FK_COMPANY2 FOREIGN KEY(AAAAAA)
    REFERENCES FOOD_COMPANY(COMPANY_ID) ON DELETE CASCADE
    -- FOOD_COMPANY 회사 ID ON DELETE CASCADE -- 부모 삭제시 자식까지 삭제해줘
);

--> CCC~  AAA~ 는 FOREIGN KEY 를 참조할 변수명
---> 참조할 변수명 FK_COMPANY2 규칙명 작성해주는데 규칙명은 모든 테이블 합쳐서 동일한 이름을 쓸 수 없음



-- 테이블 생성 DRINK_COMPANY 
CREATE TABLE DRINK_COMPANY(
    DRINK_ID NUMBER(10,0) PRIMARY KEY,
    DRINK_NAME VARCHAR2(100) NOT NULL,
    DRINK_ADDRESS VARCHAR2(255),
    DRINK_PHONE VARCHAR2(20)
    );






























/