-------- 실습 4 문제

-- ORDER BY

SELECT * FROM DEPARTMENT ORDER BY DEPT_TITLE; -- 오름차순이 디폴트 값

SELECT * FROM EMPLOYEE ORDER BY SALARY DESC; -- 내림차순을 하기 위해선 DESC 필수 입력

SELECT EMP_NAME, HIRE_DATE FROM EMPLOYEE ORDER BY HIRE_DATE;

SELECT LOCAL_NAME FROM LOCATION ORDER BY NATIONAL_CODE;

SELECT EMP_ID, EMP_NAME FROM EMPLOYEE ORDER BY EMP_NAME;


-- HAVING
-- HAVING 을 사용한다는 것은 GROUP BY 를 사용한다는 의미
-- WHERE 과 GROUP HAVING 의 차이점은
-- WHERE : 조건에 해당하는 사람들을 검색한 다음 조건에 부합하는 것 처럼 보임
-- GROUP HAVING : 모든 사람들을 조회하고 조건에 맞는 것들만 선별

SELECT DEPT_CODE, AVG(SALARY) FROM EMPLOYEE GROUP BY DEPT_CODE HAVING AVG(SALARY) > 3000000;

SELECT JOB_CODE, COUNT(*) FROM EMPLOYEE GROUP BY JOB_CODE HAVING COUNT(*) >= 3;

SELECT DEPT_CODE, SUM(SALARY) FROM EMPLOYEE GROUP BY DEPT_CODE HAVING SUM(SALARY) >= 10000000;

SELECT SAL_LEVEL, MAX(SALARY) FROM EMPLOYEE GROUP BY SAL_LEVEL HAVING MAX(SALARY) < 5000000;

SELECT DEPT_CODE, MIN(SALARY) FROM EMPLOYEE GROUP BY DEPT_CODE HAVING MIN(SALARY) >= 2000000;


-- GROUP BY

SELECT DEPT_CODE, COUNT(*) AS "직원수" FROM EMPLOYEE GROUP BY DEPT_CODE; -- ORDER BY 로 내림 오름 차순 가능

SELECT JOB_CODE, AVG(SALARY) AS "평균급여" FROM EMPLOYEE GROUP BY JOB_CODE; -- 소수점이 다 없으면 좋겠으면 FLOOR(AVG(SALARY)) 로 작성
-- FLOOR : 내림   CEIL : 올림   ROUND : 반올림

SELECT SAL_LEVEL, SUM(SALARY) FROM EMPLOYEE GROUP BY SAL_LEVEL ORDER BY SAL_LEVEL;

SELECT DEPT_CODE, MAX(SALARY) FROM EMPLOYEE GROUP BY DEPT_CODE;

SELECT JOB_CODE, MIN(SALARY) FROM EMPLOYEE GROUP BY JOB_CODE;

SELECT NATIONAL_CODE, COUNT(*) FROM LOCATION GROUP BY NATIONAL_CODE;

SELECT LOCAL_CODE, COUNT(*) FROM DEPARTMENT GROUP BY LOCAL_CODE; -- ??? 7 .

SELECT DEPT_CODE, AVG(BONUS) FROM EMPLOYEE GROUP BY DEPT_CODE;

SELECT SAL_LEVEL, COUNT(*) FROM EMPLOYEE GROUP BY SAL_LEVEL;

SELECT JOB_CODE, SUM(SALARY) FROM EMPLOYEE GROUP BY JOB_CODE;


-- WHERE 

SELECT EMP_NAME FROM EMPLOYEE WHERE SALARY >= 3000000;

SELECT EMP_NAME FROM EMPLOYEE WHERE DEPT_CODE = 'D1';

SELECT EMP_NAME FROM EMPLOYEE WHERE JOB_CODE = 'J2';

SELECT EMP_NAME FROM EMPLOYEE WHERE SAL_LEVEL = 'S4';

SELECT DEPT_TITLE FROM DEPARTMENT WHERE LOCATION_ID = 'L1';

SELECT LOCAL_NAME FROM LOCATION WHERE NATIONAL_CODE = 'US';

SELECT * FROM NATIONAL WHERE NATIONAL_NAME = '한국';

SELECT * FROM SAL_GRADE WHERE MIN_SAL >= 2000000;

SELECT EMP_NAME, BONUS FROM EMPLOYEE WHERE BONUS IS NOT NULL; -- 9번
